eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 9090

spring:
 application:
  name: lmscourses
  
 datasource:
   url: jdbc:mysql://localhost:3306/lms
   username: root
   password: root
 
   
 jpa:
  hibernate:
     ddl-auto: update
      
 config:
  import: optional:configserver:http://localhost:9095

  